create table postcodedetail (

    id bigint auto_increment,
    postcode int,
    suburb varchar(50),
    primary key (id),

 CONSTRAINT postdetailunique UNIQUE (postcode, suburb)
);

INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'CARRARANG');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'COBURN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'COOLCALALAYA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'DARTMOOR');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'DEEPDALE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'DINDILOA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'DRUMMOND COVE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'DURAWAH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'EAST CHAPMAN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'EAST NABAWA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'EAST YUNA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'ELLENDALE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'ERADU');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'ERADU SOUTH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'EURARDY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'GEORGINA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'GLENFIELD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'GREENOUGH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'HAMELIN POOL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'HICKETY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'HOWATHARRA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'KOJARENA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'MARRAH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'MEADOW');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'MINNENOOKA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'MOONYOONOOKA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'MOUNT ERIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'NABAWA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'NANSON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'NARALING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'NARNGULU');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'NARRA TARRA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'NERREN NERREN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'NOLBA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'NORTH ERADU');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6532,'NORTHERN GULLY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6434,'RAWLINNA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6434,'ZANTHUS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6436,'MENZIES');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6436,'ULARRING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6437,'LEINSTER');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6437,'SIR SAMUEL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6438,'LAKE DARLOT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6438,'LEONORA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6440,'BANDYA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6440,'BEADELL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6440,'BURTVILLE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6440,'COSMO NEWBERY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6440,'LAKE WELLS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6440,'LAVERTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6440,'NEALE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6442,'KAMBALDA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6443,'BALLADONIA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6443,'CAIGUNA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6443,'COCKLEBIDDY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6443,'DUNDAS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6443,'EUCLA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6443,'FRASER RANGE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6443,'HIGGINSVILLE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6443,'MADURA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6443,'MUNDRABILLA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6443,'NORSEMAN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6443,'WIDGIEMOOLTHA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6445,'NORTH CASCADE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6445,'SALMON GUMS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6446,'GRASS PATCH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6447,'LORT RIVER');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6447,'MOUNT NEY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6447,'SCADDAN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6447,'WITTENOOM HILLS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6448,'GIBSON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'BANDY CREEK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'BEAUMONT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'BOYATUP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'CAPE LE GRAND');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'CASCADE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'CASTLETOWN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'CHADWICK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'CONDINGUP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'COOMALBIDGUP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'DALYUP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'EAST MUNGLINUP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'ESPERANCE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'HOWICK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'MERIVALE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'MONJINGUP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'MUNGLINUP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'MYRUP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'NERIDUP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'NULSEN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'PINK LAKE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'SINCLAIR');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'WEST BEACH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6450,'WINDABOUT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6452,'BURAMINYA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6452,'CAPE ARID');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6452,'ISRAELITE BAY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6460,'GOOMALLING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6460,'HULONGINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6460,'KARRANADGIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6460,'UCARTY WEST');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6460,'WALYORMOURING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6461,'DOWERIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6461,'KOOMBERKINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6462,'HINDMARSH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6462,'MINNIVALE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6462,'UCARTY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6463,'BENJABERRING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6465,'MANMANNING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6466,'CADOUX');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6467,'BURAKIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6468,'GOODLANDS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6468,'KALANNIE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6468,'PETRUDOR');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6470,'KULJA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6472,'BEACON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6472,'BIMBIJY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6472,'CLEARY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6472,'KARROUN HILL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6472,'MOUROUBRA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6472,'REMLAP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6473,'NORTH WIALKI');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6473,'WIALKI');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6475,'BADGERIN ROCK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6475,'BOORALAMING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6475,'DUKIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6475,'KOORDA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6475,'LAKE MARGARETTE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6475,'MOLLERIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6475,'NEWCARLBEON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6476,'GABBIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6477,'BENCUBBIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6477,'WELBUNGIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6479,'BARBALIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6479,'BONNIE ROCK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6479,'DANDANNING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6479,'KARLONING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6479,'LAKE BROWN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6479,'MANGOWINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6479,'MUKINBUDIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6479,'WATTONING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6479,'WILGOYNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6480,'NUKARNI');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6484,'BULLFINCH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6484,'ENNUIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6484,'LAKE DEBORAH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6485,'COWCOWING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6485,'KORRELOCKING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6485,'NALKAIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6485,'NEMBUDDING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6485,'WYALKATCHEM');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6487,'NORTH YELBENI');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6487,'SOUTH YELBENI');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6487,'YELBENI');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6488,'NORTH TRAYNING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6488,'SOUTH TRAYNING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6488,'TRAYNING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6489,'KUNUNOPPIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6489,'NORTH KUNUNOPPIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6489,'SOUTH KUNUNOPPIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6490,'BURRAN ROCK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6490,'CHANDLER');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6490,'ELABBIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6490,'KWELKAN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6490,'NUNGARIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6490,'TALGOMINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6501,'MUCHEA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6502,'BINDOON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6502,'BINDOON TRAINING AREA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6503,'BAMBUN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6503,'BEERMULLAH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6503,'BOONANARRING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6503,'BREERA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6503,'COONABIDGEE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6503,'COWALLA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6503,'CULLALLA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6503,'GINGIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6503,'GINGINUP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6503,'GRANVILLE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6503,'LENNARD BROOK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6394,'CHANGERUP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6394,'MURADUP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6394,'ORCHID VALLEY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6394,'QUALEUP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6395,'CHERRY TREE POOL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6395,'JINGALUP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6395,'KOJONUP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6395,'LUMEAH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6395,'MOBRUP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6395,'RYANSBROOK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6396,'FRANKLAND');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6397,'ROCKY GULLY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6398,'BROKE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6398,'NORTH WALPOLE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6398,'WALPOLE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'BUCKLAND');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'BURLONG');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'CUNJARDINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'IRISHTOWN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'JENNACUBBINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'JENNAPULLIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'MALABAINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'MEENAAR');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'MOKINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'MULUCKINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'MUMBERKINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'MURESK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'NORTHAM');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'ROSSMORE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'SOUTHERN BROOK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'SPENCERS BROOK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'THROSSELL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6401,'WONGAMINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6403,'GRASS VALLEY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6405,'GREENWOODS VALLEY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6405,'MECKERING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6405,'QUELAGETTING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6405,'WARDING EAST');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6407,'CUNDERDIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6407,'WAEEL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6407,'WATERCARRIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6407,'WYOLA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6407,'WYOLA WEST');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6407,'YOUNDEGIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6409,'DOONGIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6409,'TAMMIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6409,'YORKRAKINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6410,'BUNGULLA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6410,'DAADENNING CREEK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6410,'KELLERBERRIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6410,'MOUNT CAROLINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6410,'NORTH KELLERBERRIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6411,'DOODLAKINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6411,'SOUTH DOODLAKINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6412,'BAANDEE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6412,'NORTH BAANDEE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6413,'HINES HILL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6414,'NANGEENAN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6415,'GOOMARIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6415,'KORBEL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6415,'MERREDIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6415,'NOKANING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6415,'NORPA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6415,'TANDEGIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6418,'BRUCE ROCK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6418,'YARDING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6419,'ARDATH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6420,'CRAMPHORNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6420,'MUNTADGIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6421,'BURRACOPPIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6421,'CAMPION');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6421,'SOUTH BURRACOPPIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6421,'WARRALAKIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6422,'WALGOOLAN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6423,'BOODAROCKIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6423,'CARRABIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6423,'WESTONIA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6424,'BODALLIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6424,'NORTH BODALLIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6424,'SOUTH BODALLIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6425,'DULYALBIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6425,'MOORINE ROCK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6426,'CORINTHIA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6426,'GHOOLI');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6426,'HOLLETON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6426,'MARVEL LOCH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6426,'MOUNT HAMPTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6426,'MOUNT HOLLAND');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6426,'MOUNT JACKSON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6426,'MOUNT PALMER');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6426,'PARKER RANGE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6426,'SKELETON ROCK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6426,'SOUTH YILGARN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6426,'SOUTHERN CROSS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6426,'TURKEY HILL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6426,'YELLOWDINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6427,'KOOLYANOBBING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6428,'BABAKIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6429,'BOORABBIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6429,'BULLABULLING');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6429,'COOLGARDIE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6429,'KARRAMINDIE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6429,'LONDONDERRY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6429,'MOUNT BURGES');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6429,'VICTORIA ROCK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6429,'WALLAROO');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6430,'BINDULI');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6430,'BROADWOOD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6430,'HANNANS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6430,'KALGOORLIE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6430,'KARLKURLA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6430,'LAMINGTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6430,'MULLINGAR');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6430,'PICCADILLY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6430,'SOMERVILLE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6430,'SOUTH KALGOORLIE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6430,'WEST KALGOORLIE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6430,'WEST LAMINGTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6430,'WILLIAMSTOWN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6430,'YILKARI');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6431,'BOORARA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6431,'BROWN HILL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6431,'BULONG');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6431,'EMU FLAT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6431,'FEYSVILLE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6431,'KANOWNA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6431,'KOOKYNIE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6431,'KURNALPI');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6431,'LAKEWOOD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6431,'ORA BANDA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6431,'PLUMRIDGE LAKES');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6431,'TRAFALGAR');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6431,'WARBURTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6432,'BOULDER');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6432,'FIMISTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6432,'SOUTH BOULDER');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6432,'VICTORY HEIGHTS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6433,'HANNANS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6433,'KALGOORLIE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6433,'KALGOORLIE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6434,'CUNDEELEE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6434,'FORREST');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 6434,'PARKESTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 9010,'BRISBANE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 9013,'BRISBANE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 9015,'BRISBANE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'WYNYARD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'YOLLA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'ALCOMIE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'ARTHUR RIVER');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'BRITTONS SWAMP');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'BROADMEADOWS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'CHRISTMAS HILLS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'COUTA ROCKS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'EDITH CREEK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'FOREST');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'HUNTER ISLAND');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'IRISHTOWN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'LILEAH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'MARRAWAH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'MELLA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'MENGHA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'MONTAGU');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'NABAGEENA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'NELSON BAY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'REDPA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'ROBBINS ISLAND');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'ROGER RIVER');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'SCOPUS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'SCOTCHTOWN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'SMITHTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'SOUTH FOREST');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'TEMMA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'THREE HUMMOCK ISLAND');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'TOGARI');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'TROWUTTA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'WEST MONTAGU');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7330,'WOOLNORTH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7331,'STANLEY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7466,'GORMANSTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7467,'LAKE MARGARET');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7467,'QUEENSTOWN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7468,'MACQUARIE HEADS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7468,'STRAHAN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7469,'GRANVILLE HARBOUR');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7469,'RENISON BELL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7469,'TRIAL HARBOUR');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7469,'ZEEHAN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7470,'ROSEBERY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8001,'MELBOURNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8002,'EAST MELBOURNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8003,'COLLINS STREET EAST');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8004,'ST KILDA ROAD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8005,'WORLD TRADE CENTRE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8006,'ABECKETT STREET');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8007,'COLLINS STREET WEST');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8008,'ST KILDA ROAD CENTRAL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8009,'FLINDERS LANE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8010,'LAW COURTS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8045,'MELBOURNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8051,'MELBOURNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8066,'MELBOURNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8069,'MELBOURNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8070,'MELBOURNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8071,'MELBOURNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8102,'MELBOURNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8107,'MELBOURNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8111,'MELBOURNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8120,'MELBOURNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8205,'MELBOURNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 8785,'DANDENONG');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 9000,'BRISBANE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 9001,'BRISBANE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 9002,'BRISBANE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 9005,'BRISBANE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 9007,'BRISBANE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 9009,'BRISBANE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7306,'ROLAND');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7306,'SHEFFIELD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7306,'STAVERTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7306,'STOODLEY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7306,'WEST KENTISH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7307,'BAKERS BEACH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7307,'HARFORD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7307,'HAWLEY BEACH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7307,'LATROBE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7307,'MORIARTY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7307,'NORTHDOWN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7307,'PORT SORELL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7307,'SASSAFRAS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7307,'SHEARWATER');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7307,'SQUEAKING POINT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7307,'THIRLSTANE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7307,'WESLEY VALE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'ABERDEEN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'AMBLESIDE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'DEVONPORT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'DON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'EAST DEVONPORT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'ERRIBA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'EUGENANA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'FORTH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'FORTHSIDE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'KINDRED');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'LILLICO');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'LOWER WILMOT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'MELROSE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'MIANDETTA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'MOINA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'PALOONA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'QUOIBA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'SOUTH SPREYTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'SPREYTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'STONY RISE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'TARLETON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'TUGRAH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'WEST DEVONPORT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7310,'WILMOT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'ABBOTSHAM');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'CASTRA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'GAWLER');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'GUNNS PLAINS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'LEITH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'LOONGANA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'NIETTA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'NORTH MOTTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'PRESTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'SOUTH NIETTA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'SOUTH PRESTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'SPALFORD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'SPRENT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'TURNERS BEACH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'ULVERSTONE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'UPPER CASTRA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7315,'WEST ULVERSTONE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7316,'CAMENA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7316,'CUPRONA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7316,'HEYBRIDGE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7316,'HOWTH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7316,'LOYETEA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7316,'PENGUIN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7316,'PRESERVATION BAY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7316,'RIANA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7316,'SOUTH RIANA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7316,'SULPHUR CREEK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7316,'WEST PINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'ACTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'BROOKLYN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'BURNIE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'CAMDALE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'COOEE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'DOWNLANDS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'EMU HEIGHTS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'HAVENVIEW');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'HILLCREST');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'MONTELLO');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'OCEAN VISTA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'PARK GROVE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'PARKLANDS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'ROMAINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'ROUND HILL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'SHOREWELL PARK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'SOUTH BURNIE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'UPPER BURNIE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7320,'WIVENHOE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'BLACK RIVER');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'BOAT HARBOUR');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'BOAT HARBOUR BEACH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'CHASM CREEK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'CORINNA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'COWRIE POINT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'CRAYFISH CREEK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'DETENTION');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'EAST CAM');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'EAST RIDGLEY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'EDGCUMBE BEACH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'GUILDFORD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'HAMPSHIRE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'HELLYER');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'HIGHCLERE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'LUINA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'MAWBANNA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'MONTUMANA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'MOOREVILLE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'NATONE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'PARRAWE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'PORT LATTA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'RIDGLEY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'ROCKY CAPE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'SAVAGE RIVER');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'SISTERS BEACH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'STOWPORT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'TEWKESBURY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'TULLAH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'UPPER NATONE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'UPPER STOWPORT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'WARATAH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'WEST MOOREVILLE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'WEST RIDGLEY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7321,'WILTSHIRE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7322,'SOMERSET');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'CALDER');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'DOCTORS ROCKS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'ELLIOTT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'FLOWERDALE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'HENRIETTA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'LAPOINYA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'MEUNNA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'MILABENA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'MOORLEAH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'MOUNT HICKS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'MYALLA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'OLDINA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'OONAH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'PREOLENNA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'SEABROOK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'SISTERS CREEK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'TABLE CAPE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'TAKONE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7325,'WEST TAKONE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7260,'NORTH SCOTTSDALE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7260,'SCOTTSDALE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7260,'SOUTH SPRINGFIELD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7260,'SPRINGFIELD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7260,'TONGANAH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7260,'TULENDEENA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7260,'WEST SCOTTSDALE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7261,'BRANXHOLM');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7261,'WARRENTINNA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7262,'BRIDPORT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7262,'TOMAHAWK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7262,'WATERHOUSE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7263,'ALBERTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7263,'LEGERWOOD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7263,'RINGAROOMA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7263,'TALAWA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7263,'TRENAH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7264,'BOOBYALLA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7264,'CAPE PORTLAND');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7264,'DERBY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7264,'EDDYSTONE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7264,'EDDYSTONE POINT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7264,'GLADSTONE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7264,'HERRICK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7264,'MOORINA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7264,'MUSSELROE BAY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7264,'PIONEER');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7264,'RUSHY LAGOON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7264,'SOUTH MOUNT CAMERON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7264,'TELITA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7264,'WELDBOROUGH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7265,'BANCA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7265,'WINNALEAH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7267,'BANGOR');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7267,'KAROOLA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7267,'LALLA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7267,'LOWER TURNERS MARSH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7267,'TURNERS MARSH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7268,'LILYDALE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7268,'NORTH LILYDALE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7268,'UNDERWOOD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7270,'BADGER HEAD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7270,'BEACONSFIELD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7270,'BEAUTY POINT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7270,'CLARENCE POINT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7270,'FLOWERY GULLY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7270,'GREENS BEACH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7270,'ILFRAVILLE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7270,'KAYENA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7270,'KELSO');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7270,'ROWELLA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7270,'SIDMOUTH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7270,'YORK TOWN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7275,'BLACKWALL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7275,'DEVIOT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7275,'EXETER');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7275,'FRANKFORD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7275,'GLENGARRY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7275,'HOLWELL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7275,'LANENA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7275,'LOIRA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7275,'NOTLEY HILLS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7275,'ROBIGANA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7275,'SWAN POINT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7275,'WINKLEIGH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7276,'GRAVELLY BEACH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7277,'BRIDGENORTH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7277,'GRINDELWALD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7277,'LEGANA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7277,'ROSEVEARS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7290,'HADSPEN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7291,'CARRICK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7292,'HAGLEY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7292,'QUAMBY BEND');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7292,'ROSEVALE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7292,'SELBOURNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7292,'WESTWOOD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7300,'DEVON HILLS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7300,'PERTH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7300,'POWRANNA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7301,'BISHOPSBOURNE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7301,'BLACKWOOD CREEK');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7301,'LIFFEY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7301,'LONGFORD');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7301,'TOIBERRY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7302,'BRACKNELL');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7302,'CRESSY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7302,'POATINA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7303,'BIRRALEE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7303,'CLUAN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7303,'EXTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7303,'OAKS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7303,'OSMASTON');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7303,'WESTBURY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7303,'WHITEMORE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7304,'BRANDUM');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7304,'BREONA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7304,'CAVESIDE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7304,'CENTRAL PLATEAU');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7304,'CHUDLEIGH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7304,'DAIRY PLAINS');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7304,'DELORAINE');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7304,'DOCTORS POINT');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7304,'DUNORLAN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7304,'ELIZABETH TOWN');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7304,'GOLDEN VALLEY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7304,'JACKEYS MARSH');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7304,'KIMBERLEY');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7304,'LIENA');
INSERT INTO postcodedetail(postcode,suburb) VALUES( 7304,'MAYBERRY');







